[package]
name = "cgol"
version = "0.1.0"
authors = ["Sascha Wittkowski <sascha.wittkowski@1und1.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
termion = "*"